### ISSUE TITLE
Ingestão/Deleção direta de documentos no Kernel

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac-airflow#43]
Desenvolver uma POC, baseado no documento de proposta de solução: https://docs.google.com/document/d/1f3f6m5CTr88t2mD6nPQhV6HImPwYLugSqFYuxk6hZD4/edit?ts=5d0377d1

* [x] #45 - Obtenção dos Pacotes
* [x] #53 - Leitura da Scilista de arquivo
* [x] #50 - Listagem de Documentos dos Pacotes
* [x] #52 - Deleção de Documentos no Kernel 
* [x] #51 - Registro/atualização de Documentos no Minio e no Kernel
* [x] #70 - Tratamento de exceções durante o processo de sincronização de Documentos no Minio e Kernel
